DI-894 - pivot to pulling data from Clarity
eastgenomics/dias_reports_bulk_reanalysis pull request #2
Opened 2024-05-02 09:46 UTC by jethror1

- switch to pulling data in from Clarity to get outstanding samples
  - currently takes an export from Clarity as an xlsx, will hopefully in future also handle directly querying the database but we're not there yet
  - now will use the specimen IDs from Clarity (as thats all we have) and the tests codes, then query all 002 projects for the assay to get the full sample details from there. Samples are then split by project to check for files and for running batch.
  - all querying now happens with project scope to keep DNAnexus API happy (but still in parallel to not take forever) 
- find all required files for SNV/CNV reports and Artemis up front and check archival state to ensure batch will be able to just launch everything
- fit all the above back to current functionality for generating manifests and running batch
- full of messy TODOs - will get to these later with further refactoring and clean up
- current Clarity export has ~2,700 sample entries, all searching and building project-sample data takes <1 minute

2024-05-02 09:46 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/run_reports.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/run_reports.py):

> [Line 107:13](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/run_reports.py#L107): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 119:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/run_reports.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 266:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/run_reports.py#L266): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 396:37](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/run_reports.py#L396): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`bin/utils/dx_manage.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py):

> [Line 63:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L63): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 71:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 97:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L97): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 97:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L97): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 100:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L100): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 101:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L101): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 102:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L102): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 287:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/dx_manage.py#L287): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

* In the file [`bin/utils/utils.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/utils.py):

> [Line 183:33](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/utils.py#L183): [E222](https://duckduckgo.com/?q=pep8%20E222) multiple spaces after operator
> [Line 195:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/utils.py#L195): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 226:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/utils.py#L226): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 262:10](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/utils.py#L262): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '{'
> [Line 266:9](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/dbebd661b509b58d01ddb05217f6736cce2fd91f/bin/utils/utils.py#L266): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation

2024-05-08 11:13 UTC, kjwinfield requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`bin/run_reports.py` line 521 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2#-NxMrw8x-AeU5Qjn8Flj:-NxMrw8x-AeU5Qjn8Flk:bui1976) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/51b4938b4228d7aa150735d936fc45a14a82dfe8/bin/run_reports.py#L521)):*
> ```Python
>         samples_to_codes = parse_clarity_export(args.clarity_export)
> 
>     sample_data = configure_inputs(samples_to_codes, 'CEN')
> ```

does samples_to_codes need to be set to None or should this all be in the else statement?
or will `pass` eventually be another way of setting samples_to_codes?
___
*[`bin/utils/dx_manage.py` line 45 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2#-NxMsSe85QInmtOIQIkY:-NxMsSe85QInmtOIQIkZ:bvsylnk) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/51b4938b4228d7aa150735d936fc45a14a82dfe8/bin/utils/dx_manage.py#L45)):*
> ```Python
>         '_markdup.per-base.bed.gz$',
>         '_markdup_recalibrated_Haplotyper.vcf.gz$',
>         '_markdup.reference_build.txt',
> ```

should this also end $
___
*[`bin/utils/dx_manage.py` line 53 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2#-NxMt3L1CRN3xwWYv76c:-NxMsmhlCEtny8LSjLwZ:b1grmz6) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/51b4938b4228d7aa150735d936fc45a14a82dfe8/bin/utils/dx_manage.py#L53)):*
> ```Python
>     samples = list(set([x['sample'] for x in sample_data['samples']]))
>     files = [f"{x}.*{y}" for x in samples for y in sample_file_patterns]
>     files.append(".*_excluded_intervals.bed")
> ```

this is always the project name, so could pass it here? can keep it like this if simpler?


<!-- Sent from Reviewable.io -->

2024-05-09 10:40 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2)* status: all files reviewed, 3 unresolved discussions (waiting on @kjwinfield)

___
*[`bin/run_reports.py` line 521 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2#-NxMrw8x-AeU5Qjn8Flj:-NxRvK1a-Y2Zaw2h6zDU:b-bgvh1y) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/51b4938b4228d7aa150735d936fc45a14a82dfe8/bin/run_reports.py#L521)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

does samples_to_codes need to be set to None or should this all be in the else statement?
or will `pass` eventually be another way of setting samples_to_codes?
</blockquote></details>

currently I've only implemented starting from an export of clarity and not directly connecting, once it is done then `samples_to_codes` will be in the `if` statement above, but both will need `configure_inputs()` calling
___
*[`bin/utils/dx_manage.py` line 45 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2#-NxMsSe85QInmtOIQIkY:-NxRvd7f68Knglbe3RTS:bb6un1j) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/51b4938b4228d7aa150735d936fc45a14a82dfe8/bin/utils/dx_manage.py#L45)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

should this also end $
</blockquote></details>

Done
___
*[`bin/utils/dx_manage.py` line 53 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2#-NxMt3L1CRN3xwWYv76c:-NxRvx01E6uwiw6XMirb:b-pwjxfd) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/51b4938b4228d7aa150735d936fc45a14a82dfe8/bin/utils/dx_manage.py#L53)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this is always the project name, so could pass it here? can keep it like this if simpler?
</blockquote></details>

I don't have the project name in this function so would require describing the ID and an extra query, since we're providing the project ID as scope to find_data_objects its fast to search so not sure it needs it


<!-- Sent from Reviewable.io -->

2024-05-22 08:47 UTC, kjwinfield approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-05-22 08:48 UTC, merged