Additional unit tests for 100% coverage on dx_manage
eastgenomics/dias_reports_bulk_reanalysis pull request #38
Opened 2024-07-08 14:08 UTC by jethror1

- add unit tests for `dx_manage.get_xlsx_reports`,  `dx_manage.run_batch` and `dx_manage.create_folder`
- remove `dx_manage.get_dependent_files` since not needed

2024-07-08 14:08 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`tests/test_dx_manage.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py):

> [Line 280:50](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L280): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 926:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L926): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 928:32](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L928): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to True should be 'if cond is True:' or 'if cond:'
> [Line 932:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L932): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (92 > 79 characters)
> [Line 934:32](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L934): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'
> [Line 937:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L937): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 943:17](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L943): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 961:45](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L961): [E712](https://duckduckgo.com/?q=pep8%20E712) comparison to False should be 'if cond is False:' or 'if not cond:'

2024-07-08 14:43 UTC, Yu-jinKim requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`tests/test_dx_manage.py` line 280 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38#-O1Hm8D47_8AoBaasuow:-O1Hm8D50aekPh8zJoYG:b2ni78k) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L280)):*
> ```Python
>     This is a relatively pointless test since its a single method call
>     with no return value or any other logic, but I want that dopamine
>     hit of seeing 100% coverage, so here we are ¯\_(ツ)_/¯
> ```

lol
___
*[`tests/test_dx_manage.py` line 943 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38#-O1Hn40f1ySGDRksWDMx:-O1Hn40f1ySGDRksWDMy:bb44fnm) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L943)):*
> ```Python
>         these are passed into the app input
>         """
>                 # example input args for dx_manage.run_batch
> ```

OCD triggered


<!-- Sent from Reviewable.io -->

2024-07-08 21:55 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`tests/test_dx_manage.py` line 280 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38#-O1Hm8D47_8AoBaasuow:-O1JL1mmAtkK0nf3Uod7:b2cnp7t) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L280)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

lol
</blockquote></details>

i'm the best
___
*[`tests/test_dx_manage.py` line 943 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38#-O1Hn40f1ySGDRksWDMx:-O1JL37g1DBpEFD73zEw:b-896fix) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/8b3a81ddb3c32979f2e93358c4017c30fb5057e6/tests/test_dx_manage.py#L943)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

OCD triggered
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-09 08:20 UTC, Yu-jinKim approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/38)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-07-09 08:20 UTC, merged