Improve logging of launched jobs
eastgenomics/dias_reports_bulk_reanalysis pull request #41
Opened 2024-07-29 13:29 UTC by jethror1

- improves logging of launched job IDs into a json file for storing and querying state / output files after launching
- add new function `utils.write_to_log()`
- add unit tests for new function
- adjust `dx_manage.get_launched_workflow_ids()` to split eggd_artemis job IDs from dias_reports
- adjust unit tests for above change

2024-07-29 13:29 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/run_reports.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/bin/run_reports.py):

> [Line 620:21](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/bin/run_reports.py#L620): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 626:21](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/bin/run_reports.py#L626): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals





* In the file [`tests/test_dx_manage.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/tests/test_dx_manage.py):

> [Line 582:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/tests/test_dx_manage.py#L582): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`tests/test_utils.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/tests/test_utils.py):

> [Line 1276:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/tests/test_utils.py#L1276): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 1310:5](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/tests/test_utils.py#L1310): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2024-07-30 12:30 UTC, kjwinfield requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/41)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`bin/utils/dx_manage.py` line 279 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/41#-O32aJdv816W_SD5rsgx:-O32aJdv816W_SD5rsgy:bqcpkh1) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/bin/utils/dx_manage.py#L279)):*
> ```Python
> def get_launched_workflow_ids(batch_ids) -> Union[list, list]:
>     """
>     Get analysis IDs of launched Dias reports and eggd_artemis
> ```

this doesn't just get analysis IDs now so change to add something like "job ID of eggd_artemis job"


<!-- Sent from Reviewable.io -->

2024-08-01 08:18 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/41)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`bin/utils/dx_manage.py` line 279 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/41#-O32aJdv816W_SD5rsgx:-O3C0HrK8RwJgIhcJ-sj:b-896fix) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b769a6ec982a05cafa26ded33e6801c6c5930587/bin/utils/dx_manage.py#L279)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

this doesn't just get analysis IDs now so change to add something like "job ID of eggd_artemis job"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 08:21 UTC, kjwinfield approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-08-01 08:21 UTC, merged