check job states and handle fails in downloading
eastgenomics/dias_reports_bulk_reanalysis pull request #50
Opened 2024-08-08 12:06 UTC by jethror1

- added new function `dx_manage.check_job_states`
  - used to check state of jobs before downloading, any failed/terminated will print a warning to stdout but not raise an error
  - any in progress jobs will cause a warning to print and for it to exit to not download partial outputs
  - add unit tests for new function
- changes to download logic to handle failed / terminated runs and missing outputs

2024-08-08 12:06 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`bin/utils/dx_manage.py`](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b8b8886296b53accbb4e8c8498c94ab37f52fdef/bin/utils/dx_manage.py):

> [Line 121:80](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/b8b8886296b53accbb4e8c8498c94ab37f52fdef/bin/utils/dx_manage.py#L121): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)

2024-08-08 12:25 UTC, kjwinfield requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/50)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`bin/run_reports.py` line 679 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/50#-O3lwp8n-Z5AwxZ5ArRR:-O3lwp8n-Z5AwxZ5ArRS:be2m4pq) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/573ffcc13b0da2083a1fff02f376ddd8247d69c7/bin/run_reports.py#L679)):*
> ```Python
>         print(
>             f"WARNING: {len(all_job_states['in_progress'])} jobs are still in "
>             f"progress. Will not download any reports until these complete."
> ```

sorry if this is obvious elsewhere - does this then go on to download once complete?


<!-- Sent from Reviewable.io -->

2024-08-12 08:09 UTC, jethror1 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/50)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`bin/run_reports.py` line 679 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/50#-O3lwp8n-Z5AwxZ5ArRR:-O44_9aG2411hlRuAbWj:b46at5a) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/573ffcc13b0da2083a1fff02f376ddd8247d69c7/bin/run_reports.py#L679)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

sorry if this is obvious elsewhere - does this then go on to download once complete?
</blockquote></details>

it will just exit and then need rerunning until there aren't any in progress jobs, I was going to add something to print all job states from the log file later. Not sure if it was essential for v1 though so might be a backlog thing


<!-- Sent from Reviewable.io -->

2024-08-12 08:26 UTC, kjwinfield approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/50#-:-O44g3NL7021ybi5Bi_R:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2024-08-12 08:26 UTC, merged